# Generated by Django 5.2.10 on 2026-02-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('disease', models.CharField(max_length=255)),
                ('phase', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trials.clinicaltrial')),
            ],
        ),
    ]
